# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]

        thumbOutbound:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound

        test:
            filters:

            # use and setup the "fixed" filter
                fixed:

                # set the fixed size to "120x90" pixels
                    width: 360
                    height: 270
        test4:
            filters:

                # use and setup the "downscale" filter
                downscale:

                    # input 3960x2560px -> output 1980x1280px
                    max: [360, 300]